== Migration Guide

Guide to migrate your applications between different version.
JGroups Raft follows the usual semantic versioning for releases.
Patch releases should work out-of-the-box without further changes from the application's perspective.
Major and minor might require some extra steps to continue working (migration scripts, public API updates, etc).

=== 1.1.0

For users upgrading from 1.0.x to 1.1.x.

==== LevelDBLog is deprecated

To remove the use of abandonware, we marked `LevelDBLog` as deprecated and its implementation now delegates to `FileBasedLog`.
Since these logs utilize different formats, a migration procedure is needed to keep your data intact.
We have developed a script utilizing https://www.jbang.dev/[JBang] to migrate from `LevelDBLog` to `FileBasedLog`.
This procedure will migrate the existing files to the expected format and keep the original data.

The migration script is located under the `bin` folder in the project root with name `migrate_leveldb.java`.
These scripts are not shipped with the release.
Suppose you utilized JGroups Raft with LevelDB pointing to folder `/home/raft/data`.
You can utilize the migration script as:

[source,bash]
----
$ ./bin/migrate_leveldb.java /home/raft/data
----

This will read the data files at the given folder and transform to the expected format.
If the procedure fails during the migration, the new files will be cleaned up.
The new data will be placed in the same folder, so you can restart your application without changing properties.

If there is already data files with the format expected by the `FileBasedLog` the script will not run and exit.
To run the migration tool and ignore the existing files, use the `--force` flag when invoking the script.
This will copy the existing data to a `temp` folder (`/home/raft/data/temp`, using the previous example) and will proceed with the migration.
If there is a `temp` folder already, the script will not run.


NOTE: JBang allows running remote scripts. See https://www.jbang.dev/documentation/guide/latest/usage.html#urls-from-trusted-sources[JBang] for more information.
