
= Design
Author: Bela Ban


== Architecture
* Below is an overview of the architecture:

----

 -------------------
 |  StateMachine   | <---
 | implementation  |     |
 -------------------     |
           |             |
           |             |
    -------------        |
    |  Channel  |        |
    -------------        |
           |             |
      ----------         |
      | CLIENT |         |
      ----------         |
           |             |
      -----------        |
      |         |  ------
      |  RAFT   |
      |         |  --> Log
      -----------
           |
      -----------
      | ELECTION |
      ------------
----

* Protocols are `CLIENT`, `RAFT` and `ELECTION`
. `CLIENT` handles the set(), get() and remove() events from above (e.g. a building block) and passes them down to the
  `RAFT` protocol. This protocol could also provide a REST interface, e.g. to handle requests from etcd
. RAFT handles requests according to its role (follower, candidate, leader) and talks to Log and StateMachine
** It has references to a `Log` and a `StateMachine`
** E.g. a follower or candidate sends a redirect to a client if an operation is invoked
. `ELECTION` performs leader election and passes up BECOME_<ROLE> (e.g. BECOME_LEADER) events to RAFT. It also performs
   heartbeating (only a leader does this) to keep followers from becoming candidates
* `Log` handles the persistent log
** By default, all prepares and commits are written to stable storage, but this protocol could be replaced by a
   pure in-memory implementation
* `StateMachine` implements a state machine. Log entries can be applied to it


== CLIENT
* Handles commands such as `set()`, `get()` and `remove()` sent from above
* Handles redirection to leader (?)
** Buffers commands if no leader is present ?




== RAFT
* This protocol handles leader election, heartbeating, election timeouts and log replication and safety
** The log reads and writes themselves are handled by `LOG`
* The role pattern is used. We have 3 classes
Follower:: Initial state. When run into the election timeout, becomes Candidate and starts an election
Candidate:: Waits for election responses. Becomes Leader if it wins the election, or goes back to Follower if it loses
            the election
Leader:: Starts the heartbeat. Goes back to Follower is it sees a message with a higher term. Handles all client requests
         by sending them to the followers and committing them in case of a majority response.

There's a common superclass `RaftImpl` which handles all of the common state and other ancilary functions (e.g. timers).

=== Properties
heartbeat_interval:: Interval (in ms) at which the heartbeats are set (default: 50 ms)

election_min_interval:: Min interval for election timer (default: 150 ms)

election_max_interval:: Max interval for election timer (default: 300 ms). The election timeout is a randomized value
                        between `election_min_interval` and `election_max_interval`.
majority:: The majority needed to win an election or commit a log entry. Will be set dynamically when view
           changes are implemented, so this property will get removed then)

=== Fields
view:: The current view

leader:: The current leader (null if none has been elected yet)

current_term:: The current term

voted_for:: The address of the candidate this node voted for in the current term

heartbeat_task:: Task which sends a heartbeat periodically. Only run in the leader.

election_task:: Task which runs periodically to see if an election is needed

role:: An instance of `RaftImpl`; `Follower`, `Candidate` or `Leader`


=== RaftImpl
==== Fields
prot:: A reference to the RAFT protocol in which the instance is created. This way, fields of RAFT can be accessed

==== Behavior

===== On init
* Start the election timer
* Stop the heartbeat task

===== On reception of a heartbeat
* Reset the election timer







=== Follower

==== Behavior

===== On


=== Candidate



=== Leader

===== On init
* Start the heartbeat task
* Stop the election timer




== LOG


