
RAFT in JGroups
===============

Goals
-----
. Implement the RAFT consensus protocol in JGroups
. Provide an API to RAFT
. Implement etcd (?) [API and REST interface]
. ZooKeeper impl using etcd impl (?)
. View installation via consensus ?


Advantages of using JGroups as basis for a RAFT impl
----------------------------------------------------
* Transports already available: UDP, TCP
** Contains thread pools, priority delivery (OOB), batching etc
* Variety of discovery protocols
* Encryption, authentication, compression
* Fragmentation, reliability over UDP
* Multicasting for larger clusters
* Failure detection
* Sync/async cluster RPC


Design overview
---------------
* Raft building block over a channel
** Communicates with RAFT protocol via events (like COUNTER or CENTRAL_LOCK)


Design issues
-------------
* Separate protocols for
** Leader election
*** Could be omitted as JGroups already has a leader
**** No, we cannot use this (see below under Issues) !
**** But we may be able to reuse the JGroups failure detection protocols for the heartbeat
*** Majority partition makes progress
** Log replication
** Log safety
** Client interaction
* These protocols would communicate via events
* Heartbeat is not needed for failure detection, but only for log replication
  and log safety


Misc
----
* Seperate GitHub project for now for RAFT protocol and building block
** May be moved into JGroups once it is stable
** But for now, with a separate project we can release quickly and independently
* Separate project for etcd consuming RAFT and JGroups ?
* Mailing list on google
** Potential contributors from Lyon and Newcastle uni (MarkL)
*** Julien Ponge: julien.ponge@insa-lyon.fr


Issues
------
* What happens with client requests when no leader is elected ?
** Are they queued ?

* Do clients block until consensus has been reached, before they get the result ?
** For a get() this makes sense, but for a write ?

* Log replication message: sent to all, or only to those which have missing log entries ?
** Probably to all, as this also serves as heartbeat
*** Not very efficient to send *all* missing log entries to *all* members !

* We cannot use JGroups leader election (coordinators) because *a new leader may not contain
  all of the committed log entries !*
  ** In RAFT's leader election algorithm, only candidates will all (or the most) committed entries can become leaders









